Repository MCSManager/MCSManager, pull requests merged in 2025-07, with the labels that each got.

#1673 feat: operation logger
  daemon/src/routers/Instance_router.ts
  frontend/components.d.ts
  frontend/src/config/index.ts
  frontend/src/hooks/useOperationLog.ts
  frontend/src/services/apis/operationLog.ts
  frontend/src/types/operationLog.ts
  frontend/src/widgets/OperationLogCard.vue
  panel/src/app/common/storage/jsonl_storage.ts
  panel/src/app/routers/daemon_router.ts
  panel/src/app/routers/filemananger_router.ts
  panel/src/app/routers/instance_admin_router.ts
  panel/src/app/routers/instance_operate_router.ts
  panel/src/app/routers/login_router.ts
  panel/src/app/routers/manage_user_router.ts
  panel/src/app/routers/overview_router.ts
  panel/src/app/routers/schedule_router.ts
  panel/src/app/routers/settings_router.ts
  panel/src/app/service/operation_logger.ts
  panel/src/app/service/user_service.ts
  panel/src/types/operation_logger.ts
Labels: Pull request

#1680 Feat: Add resource usage display for Docker containers
  daemon/src/entity/commands/dispatcher.ts
  daemon/src/entity/commands/task/docker_stats.ts
  daemon/src/entity/instance/instance.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/tools.scss
  frontend/src/types/index.ts
  frontend/src/widgets/instance/BaseInfo.vue
Labels: Pull request

#1679 feat: run as user
  common/global.d.ts
  daemon/src/entity/commands/general/general_start.ts
  daemon/src/entity/commands/pty/pty_start.ts
  daemon/src/entity/instance/Instance_config.ts
  daemon/src/entity/instance/instance.ts
  frontend/src/widgets/instance/dialogs/InstanceDetail.vue
  languages/en_US.json
Labels: Pull request, New Feature

#1676 feat: Iteration-dev-2025-7
  .vscode/settings.json
  common/global.d.ts
  daemon/src/app.ts
  daemon/src/entity/commands/dispatcher.ts
  daemon/src/entity/commands/general/general_start.ts
  daemon/src/entity/commands/pty/pty_start.ts
  daemon/src/entity/commands/task/docker_stats.ts
  daemon/src/entity/file_writer.ts
  daemon/src/entity/instance/Instance_config.ts
  daemon/src/entity/instance/instance.ts
  daemon/src/routers/http_router.ts
  daemon/src/service/docker_process_service.ts
  daemon/src/service/system_instance.ts
  daemon/src/service/upload_manager.ts
  daemon/src/tools/system_user.ts
  frontend/components.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/tools.scss
  frontend/src/components/TerminalTags.vue
  frontend/src/components/interface.ts
  frontend/src/config/index.ts
  frontend/src/hooks/useFileManager.ts
  frontend/src/hooks/useOperationLog.ts
  frontend/src/services/apis/fileManager.ts
  frontend/src/services/uploadService.ts
  frontend/src/tools/fileSize.ts
  frontend/src/tools/fileSum.ts
  frontend/src/types/index.ts
  frontend/src/widgets/OperationLogCard.vue
  frontend/src/widgets/RequestChart.vue
  frontend/src/widgets/instance/BaseInfo.vue
  frontend/src/widgets/instance/FileManager.vue
  frontend/src/widgets/instance/Terminal.vue
  frontend/src/widgets/instance/dialogs/InstanceDetail.vue
  languages/de_DE.json
  languages/en_US.json
  languages/es_ES.json
  languages/fr_FR.json
  languages/ja_JP.json
  languages/ko_KR.json
  languages/pt_BR.json
  languages/ru_RU.json
  languages/th_TH.json
  languages/tr_TR.json
  languages/zh_CN.json
  package.json
  panel/src/app.ts
  panel/src/app/entity/remote_service.ts
  panel/src/app/middleware/permission.ts
  panel/src/app/routers/overview_router.ts
  panel/src/app/service/frontend_layout.ts
Labels: Pull request, BUG FIX, New Feature

#1692 Fix/upload
  common/package-lock.json
  daemon/package-lock.json
  frontend/src/config/index.ts
  frontend/src/services/uploadService.ts
  frontend/src/widgets/InstanceChart.vue
  frontend/src/widgets/NodeOverview.vue
  frontend/src/widgets/OperationLogCard.vue
  frontend/src/widgets/instance/FileManager.vue
  panel/src/app/service/frontend_layout.ts
Labels: BUG FIX
